env_name: isaacsim

app:
  width: 1280
  height: 720 
  sync_loads: True
  headless: False
  renderer: RayTracedLighting

# usd_path: omniverse://localhost/Library/NVIDIA/Assets/Isaac/2023.1.1/Isaac/Environments/NYU/NYC_sim.usd
usd_path: omniverse://localhost/Library/NVIDIA/Assets/Isaac/2023.1.1/Isaac/Environments/NYU/NYC_street.usd
grid_resolution: 1.0

robot:
  robot_name: crazyflie
  sensors: camera
  init_position: [1.5, 0.0, 60.0]
  init_orientation: [0.0, 0.0, 0.0]
  num_observations: 18

camera:
  frequency: 20
  resolution: [1920, 1200]
  translation: [0, 0, 0.05]
  orientation: [0, 0, 0]
  visualization: True
  
lidar_forward:
  frequency: 20
  range: [0.4, 250.0]
  fov: [360.0, 70.0]
  resolution: [0.2, 0.4]
  rotation_rate: 0.0
  orientation: [0.0, 0.0, 0.0]
  translation: [0.0, 0.0, 0.05]
  draw_lines: False
  display_points: True
  multi_line_mode: True
  enable_semantics: True
  visualization: False
  
lidar_downward:
  frequency: 20
  range: [0.4, 100.0]
  fov: [90, 90]
  resolution: [1.0, 1.0]
  rotation_rate: 0.0
  orientation: [0.0, 90.0, 0.0]
  translation: [0.0, 0.0, 0.0]
  draw_lines: False
  display_points: True
  multi_line_mode: True
  enable_semantics: True
  visualization: False

env:  
  groundplane_z: -2.0
  num_envs: 1 # ${resolve_default:1,${...num_envs}}
  env_spacing: 5 
  gravity: [0.0, 0.0, -9.81]
  map_size: 100
  num_waypoints_per_plan: 10000  # set to a large number since we only do open loop for sim
  max_plan_iter: 1
  visualize: True
  
  
controller:
  horizon_length: 1
  num_samples: 10000
  ee_local: temperature
  ee_local_radius: 0.15

visualizer:
  save_dir: ./visualizations
  quality: low
  map_size: 100

    
  
